### ISSUE TITLE
EPA Upgrade/Clean needs to fix incomplete EPA Keywords thesaName Section

### ISSUE THREAD

**Issue by dspinosa** [USEPA/EPA-Metadata-Editor-Pro#100]
thesaName and thesaLang incomplete and/or missing with the off-the-shelf upgrade.

![image](https://user-images.githubusercontent.com/5093530/98695501-9080f800-2327-11eb-9ce2-117684a21438.png)

![image](https://user-images.githubusercontent.com/5093530/98696085-39c7ee00-2328-11eb-8897-54e6eb71483c.png)

**Comment by jmaxmarno** [comment]
- remove existing thesaName component, insert static thesaName, and thesaLang components
 - same for Program Codes
 - Place Keywords
 - check for User Keywords
