### ISSUE TITLE
Addin Install and Toolbar ScreenShots

### ISSUE THREAD

**Issue by dspinosa** [USEPA/EPA-Metadata-Editor-Pro#113]

**Comment by dspinosa** [comment]
![image](https://user-images.githubusercontent.com/5093530/99739235-27b12280-2a81-11eb-986d-424528158115.png)

**Comment by dspinosa** [comment]
![image](https://user-images.githubusercontent.com/5093530/99740069-110bcb00-2a83-11eb-8a81-f0ffc2d523a1.png)

**Comment by dspinosa** [comment]
@jmaxmarno  upload a new Screen shot and then update the wiki, putting the new link and put the tools in the correct order.

**Comment by jmaxmarno** [comment]
![image](https://user-images.githubusercontent.com/9143887/99742671-3acbee80-2a91-11eb-9180-2ca7d8b2be9f.png)

**Comment by jmaxmarno** [comment]
![image](https://user-images.githubusercontent.com/9143887/99742883-b0d05580-2a91-11eb-9642-d64d00eaa3d9.png)

**Comment by dspinosa** [comment]
![image](https://user-images.githubusercontent.com/5093530/99818559-3a6c3b80-2b03-11eb-86b5-f2a70903fb05.png)

**Comment by jmaxmarno** [comment]
![image](https://user-images.githubusercontent.com/9143887/99818003-e49b9180-2b0a-11eb-9b65-a35448bfd9fa.png)
