### ISSUE TITLE
Remove validation error "The tags element should be empty"

### ISSUE THREAD

**Issue by torrin47** [USEPA/EPA-Metadata-Editor-Pro#117]
Now that we have the sweet copy keywords to tags tool this message is no longer necessary or appropriate.

**Comment by dspinosa** [comment]
and include a UI hint that tags should be populated using the new Keywords to Tags tool.

**Comment by torrin47** [comment]
@dspinosa Got this finished and updated the tooltip text to give a UI hint, but finding that none of the tooltips are actually being displayed, in any text fields, in any version of the tool, or even the base Esri metadata editor with no customization. Am I crazy? Did tooltips work at any point?

**Comment by torrin47** [comment]
I think I found the answer to my question and I'm going to capture it here.  If memory serves, ArcMap showed tooltips not as hovertips by the cursor, but in a dedicated area at the bottom of the window (tidy perhaps, but also easily overlooked or ignored). The editor interface in pro doesn't have a similar area, so at the moment, even though the toolkit provides for toolkits, they're never displayed. Esri acknowledges this here:

https://github.com/Esri/arcgis-pro-metadata-toolkit/wiki/Create-a-custom-page

> NOTE: At the present time, the ArcGIS Pro metadata editor does not have a central location to display ToolTip properties that provide guidance about the content to enter for a metadata element. Therefore, ToolTip properties will not be added in the following steps, and the associated string resources are not provided here.

Hopefully this will be addressed in a future release? In the meantime should probably not put too much effort into tooltips. Frustrating.

**Comment by torrin47** [comment]
Found a workaround - even though the text box itself won't display a tooltip, the label/title above the textbox will. It's not ideal, but better than nothing.
