### ISSUE TITLE
addin not forward compatible

### ISSUE THREAD

**Issue by jmaxmarno** [USEPA/EPA-Metadata-Editor-Pro#126]
### The addin does not install when running ArcGIS Pro 2.7
- confirmed on 1/6/2020 with Ali Scott of Innovate

Per [these docs](https://github.com/Esri/arcgis-pro-sdk/wiki/ProConcepts-Advanced-Topics#add-in-versioning)
"Add-ins and configurations are forwards compatible across all minor versions of ArcGIS Pro. Add-ins and configurations are not forward compatible across major versions (eg 2.x, 3.x, etc). Add-ins and configurations are not backwards compatible across any versions of ArcGIS Pro."

**Comment by MapGirl18** [comment]
Just updated Pro to 2.7.2, and installed the Add-In. Have not tested thoroughly yet.

**Comment by MapGirl18** [comment]
Installed, but tools do not work as described. For example, metadata with mixed content (ArcGIS and FGDC CSDGM) does not upgrade properly - the upgrade tool erases all the content.

**Comment by torrin47** [comment]
Seems to generally work through EME 2.9. Pro 3 breaks everything, though, with a rebasing on .NET 6 from v4.8. Esri has not yet released a 3.x compatible version of the toolkit (https://github.com/Esri/arcgis-pro-metadata-toolit) as of the release of 3. Hopefully we can continue to use this repo for further development. This issue, though, isn't a bug we can actually fix.  Closing.
