### ISSUE TITLE
EPA Upgrade FGDC to ArcGIS tool does not work with spaces in the folder structure

### ISSUE THREAD

**Issue by charness39** [USEPA/EPA-Metadata-Editor-Pro#128]
The Upgrade FGDC to ArcGIS tool does not work with spaces in the folder structure. The following error is recieved:

 *Upgrade process skipped for 'C:\Projects\EDG2020\EME_ArcGISPro\Test For User\NAA1987PM10_org.xml' due to space found in name. 

A user submitted this as a support request. I tested and received the same results.

**Comment by torrin47** [comment]
Addressed in upcoming release.
