### ISSUE TITLE
thumbnail generator

### ISSUE THREAD

**Issue by jmaxmarno** [USEPA/EPA-Metadata-Editor-Pro#47]
- [x] update thumbnails

- [x] basemap selector

**Comment by dspinosa** [comment]
Maybe use the scratch workspace option instead of your user name path?  See line 125 in EMEMenu.cs

**Comment by dspinosa** [comment]
First iteration create a picklist that includes None as an option, set default to project default (or manually pick a default).  If possible get the basemap gallery picker.
![image](https://user-images.githubusercontent.com/5093530/94071491-d51cf800-fda8-11ea-97f5-74b9161e7364.png)
