### ISSUE TITLE
highlight nested validation errors in editor

### ISSUE THREAD

**Issue by jmaxmarno** [USEPA/EPA-Metadata-Editor-Pro#53]
## Validation errors are difficult to find especially if occurring on a nested element

- [ ] flag parent element(s) as well

![image](https://user-images.githubusercontent.com/9143887/88187016-3da5f800-cbf3-11ea-9621-2253fb1cae72.png)
vs...

![image](https://user-images.githubusercontent.com/9143887/88187075-4dbdd780-cbf3-11ea-9391-2934f7af6261.png)

**Comment by dspinosa** [comment]
Maybe just a flag or red highlighting at the parent level... if the child element doesn't exist.  If it exists, try to highlight the path of elements leading to the validation error, or auto-expand.

**Comment by jmaxmarno** [comment]
could use check and x as in the side panel - from 10/14 meeting
![image](https://user-images.githubusercontent.com/9143887/96149242-1a7ba380-0ed7-11eb-82f6-3a49c9342f35.png)

**Comment by jmaxmarno** [comment]
This is no longer part of the road map - we are creating custom validation messages instead since it is not feasible to highlight controls within the validation framework
