### ISSUE TITLE
Discuss Existing Style Guide

### ISSUE THREAD

**Issue by dspinosa** [USEPA/EPA-Metadata-Editor-Pro#7]
Modify the existing or create a new?
https://www.epa.gov/geospatial/epa-geospatial-metadata-style-guide-using-eme-5#description
e.g., Item Info "Info Icon"

**Comment by jmaxmarno** [comment]
Style guide urls should be defined once, and referenced in all pages rather than hardcoded in each wpf.

**Comment by jmaxmarno** [comment]
now has url redirect
url has been updated in xaml pages
style guide tip has been updated (EME 5.0 Style Guide >> EME Style Guide)
