### ISSUE TITLE
synchronization

### ISSUE THREAD

**Issue by jmaxmarno** [USEPA/EPA-Metadata-Editor-Pro#75]
figure out appropriate settings for synchronization options for python tools, and auxiliary EME tools button

https://pro.arcgis.com/en/pro-app/help/metadata/update-item-properties-in-metadata.htm

https://pro.arcgis.com/en/pro-app/arcpy/metadata/metadata-class.htm#C_GUID-ED041163-664D-4982-9CBC-86A9F2332D11

**Comment by dspinosa** [comment]
created a tool for this.
