### ISSUE TITLE
Review EME v5 Enhancement List with EME Team

### ISSUE THREAD

**Issue by dspinosa** [USEPA/EPA-Metadata-Editor-Pro#8]
https://github.com/USEPA/EPA-Metadata-Editor-5/labels/enhancement
and
https://github.com/USEPA/EPA-Metadata-Editor-Pro/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement

**Comment by torrin47** [comment]
Conducted full review of EME 5 backlog now that ArcGIS Desktop is at end-of-life.  Closed most issues as "wontfix" and transferred a few over to this backlog.
