### ISSUE TITLE
CSDGM-ArcGIS Keyword section component issues

### ISSUE THREAD

**Issue by dspinosa** [USEPA/EPA-Metadata-Editor-Pro#95]
On upgrade, Keyword sections do not appear to be built to EPA spec. 

a) Two keyword sections are created from the ISO 19115 Topic Category Section.... dataIdInfo/tpCat and dataIdInfo/themKeys/(with thesaName=  ISO 19115 Topic Category).  Resolution would be to remove this componnent :  dataIdInfo/themeKeys/thesaName/[resTitle='ISO 19115 Topic Category']

b) The sections for EPA Keywords and Place do not have EPA compliant section for dataIdInfo/placeKeys/thesaName &  dataIdInfo/themeKeys/thesaName.  Resolution:  After you delete and add back the sections they are properly built.

**The date validation issues go away when using the latest 19115 configuration (daml), however the section are still not built "correctly"

**Comment by torrin47** [comment]
a) agree with proposed resolution - any idea what causes the extra section?
b) can this be fixed as part of the EPA upgrade, or does it have to be a two-step process? Is this new to Pro, or does this behavior date back to ArcCatalog tool?

**Comment by dspinosa** [comment]
The extra section appears to be caused by the out of the box ArcGIS upgrade process.  I would suspect this also happed in EME5 since it was also using a similar out of the box upgrade, however I can't get the EME 5x py tools to work for me anymore.

Item "a" should be an easy fix.  I'm thinking through a fix for item "b" above.
